package com.handtruth.mc.mcsman.common.access

object GlobalPermissions {
    const val service = "service"
    const val session = "session"
    const val serverList = "server_list"
    const val volumeList = "volume_list"
    const val userList = "user_list"
    const val groupList = "group_list"
    const val globalPermList = "global_list_perm"
    const val globalCheck = "global_check"
    const val imageCheck = "image_check"
    const val imagePermList = "global_list_perm"
    const val mkServer = "mk_server"
    const val mkUser = "mk_user"
    const val mkGroup = "mk_group"
    const val chGroup = "ch_group"
    const val chSelf = "ch_self"
    const val chUser = "ch_user"
    const val getUser = "get_user"
    const val getGroup = "get_group"
    const val searchUser = "search_user"
    const val searchGroup = "search_group"
    const val blockUser = "block_user"
    const val rmUser = "rm_user"
    const val rmSelf = "rm_self"
    const val rmGroup = "rm_group"
    const val grantGlobal = "grant_global"
    const val revokeGlobal = "revoke_global"
    const val grantImage = "grant_image"
    const val revokeImage = "revoke_image"
    const val event = "event"
    const val chSelfPasswd = "ch_self_passwd"
    const val chPasswd = "ch_passwd"
    const val admin = "admin"
}
